version: "3.9"

services:

  # Container 1 - Flask Application
  app:

    image: chetan8889/expense-tracker-enterprise:latest

    container_name: expense-tracker-app

    ports:
      - "5001:5000"

    env_file:
      - .env

    depends_on:
      - mysql

  # Container 2 - MySQL Database
  mysql:

    image: mysql:8.0

    container_name: expense-tracker-db

    restart: always

    environment:

      MYSQL_ROOT_PASSWORD: Chetan@23

      MYSQL_DATABASE: expense_tracker_enterprise

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

volumes:

  mysql_data: