version: "3.9"

services:

  # ======================================
  # Flask Application
  # ======================================

  app:

    image: chetan8889/expense-tracker-enterprise:latest

    container_name: expense-tracker-app

    restart: unless-stopped

    ports:
      - "5001:5000"

    env_file:
      - .env

    depends_on:
      - mysql

    networks:
      - expense-network


  # ======================================
  # MySQL Database
  # ======================================

  mysql:

    image: mysql:8.0

    container_name: expense-tracker-db

    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - expense-network


# ======================================
# Docker Volumes
# ======================================

volumes:

  mysql_data:


# ======================================
# Docker Networks
# ======================================

networks:

  expense-network: