apiVersion: v1
kind: ConfigMap

metadata:
  name: expense-tracker-config

data:
  MYSQL_HOST: "mysql"
  MYSQL_USER: "root"
  MYSQL_DB: "expense_tracker_enterprise"

  AWS_REGION: "ap-south-1"
  S3_BUCKET: "expense-tracker-bucket"

  FLASK_ENV: "production"
